title: StringFuzz
description: >
    StringFuzz is a fuzzer for string SMT solvers. This web site has links
    to the source code, documentation, experiments, benchmarks, and papers
    related to StringFuzz.

baseurl: ""
url: "stringfuzz.dmitryblotsky.com"

timezone: UTC

markdown: kramdown
kramdown:
  input: GFM

highlighter: rouge

collections:
  results:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: results
    values:
      layout: result

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
