title: StringFuzz
description: >
    String Fuzz is an SMT 2.x fuzzer. This web site has links to the source,
    documentation, experiments, and papers related to the fuzzer.

baseurl: ""
url: "stringfuzz.dmitryblotsky.com"

email: dmitry.blotsky@gmail.com
twitter_username: dblotsky
github_username: dblotsky

markdown: kramdown

collections:
  results:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: results
    values:
      layout: result

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
